src/Entity/UserInfo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserInfoRepository;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserInfoRepository::class)
 */
class UserInfo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    // ajax fonctionnement cascade clé user

    /**
     * @ORM\Column(type="string", length=5)
     * @Assert\Regex(pattern="/^[0-9]{5}$/", message="Ceci n'est pas un code postal")
     */
    private $zipCode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=1, minMessage="Le nom de la ville est trop court", max=255, maxMessage="Le nom de la ville est trop long")
     */
    private $City;

    /**
     * @ORM\ManyToOne(targetEntity=Sport::class, inversedBy="userInfos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $favoriteSport;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="userInfo", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getFavoriteSport(): ?Sport
    {
        return $this->favoriteSport;
    }

    public function setFavoriteSport(?Sport $favoriteSport): self
    {
        $this->favoriteSport = $favoriteSport;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(User $users): self
    {
        $this->users = $users;

        return $this;
    }
}

src/Controller/MyAccountController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\UserInfo;
use App\Form\UserEditType;
use App\Form\UserInfoType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MyAccountController extends AbstractController
{
    /**
     * @Route("/profile/myaccount", name="my_account")
     */
    public function index()
    {
        return $this->render('my_account/index.html.twig', [
            'controller_name' => 'MyAccountController',
        ]);
    }

    /**
     * @Route("/profile/{id}/edit", name="user_edit_profile")
     */
    public function user_edit_profile(User $user, Request $request, EntityManagerInterface $manager, UserInfo $userinfo)
    {
        $form = $this->createForm(UserInfoType::class, $userinfo);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $manager->persist($userinfo);
            $manager->flush();
            $this->addFlash('success', 'Modifié avec succès');

            return $this->redirectToRoute('my_account');
        }

        return $this->render(
            'my_account/profile_user_edit.html.twig',
            [
                'user' => $user,
                'userinfo' => $userinfo,
                'form' => $form->createView()
            ]
        );
    }
}

templates/my_account/index.html.twig
{% extends 'base1.html.twig' %}

{% block title %}WeSport | Mon Compte{% endblock %}

{% block body %}
<h1 class="jumbotron text-center">Mon Compte</h1>
<div class="container bloc-home">


    <p class="monCompte">Mon pseudo: {{ app.user.username }}</p>
    <p class="monCompte">Mon email: {{ app.user.email }}</p>
    <p class="monCompte">Mon sport favori: {{ app.user.userInfo.favoriteSport.sportName}} <a
            href="{{path('user_edit_profile', {id: app.user.id})}}">Modifier votre sport favori</a></p>
    <p class="monCompte">Mon code postal: {{ app.user.userInfo.zipCode}}</p>
    <p class="monCompte">Ma ville: {{app.user.userInfo.city}}</p>

</div>
{% endblock %}

templates/my_account/profile_user_edit.html.twig
{% extends "base1.html.twig" %}

{% block title %}
WeSport | Modifier mon compte
{% endblock %}

{% block body %}
<div class="container bloc-home">
    {{ form_start(form)}}


    {{form_row(form)}}

    <button class="btn btn-primary">Enregister les modifications</button>
    {{ form_end(form)}}
</div>
{% endblock %}